before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: V9swwaLjGX2c5dmgn3HWkTjHiKHQ86UZR78t90Q4j7kcMwDBdHd8vLNConnmDTYv/+c3mJ+uzq7hhyC/1qlHX++dUG+U2UuhQYA7wICrlWWvj9a0FS6Mevm65Zy0GtujRYxHlJHE1i7ALReVV6rtxRH2693x51OLLTOVxOKXQz489W+Rd1OaFSvGOwnCM7Z/nDYSFeAX9mQozcIETUmmLxFAG3C4mtxsY5iLzay0XXBH9q2P+zp2vKKyqCR+3HT5wzs1BUPyBOwuu94GEFJGGX2AMUXKGOipKHzvnNclpVj3A3SnTySkwcOZfgse41uJ+NlFcOIjVNG7aeZqKsbUIBHCpODoBb4RBovKtaxJR3qi+iQMOcgYc0qw4JzQaTIeVQNX/mNkNzG4XCYD/gk1c+c/3SYSTqOlDF35Ev0/rUhNds5JfqqLX1Tmg/WsrxVoPalL8HBsIf3y1bSwsf6ovaRiOH7qDvnB82qW/zXAL2k4J+PRyK6jGedhNJsZE4Cx/4iCLkqC+zKD8X1FtmiWXo/pqDOlGOCr9h6RfLTa85haTnNtsfOWDiSlq2/v5H21sGU3Mod3R2lezRlK2eGZRV0BWmyeH1qxSdjJjzo/YEmOjpHL1Er1Th13PjiOzjbVAqWiZuWPcbVQvRwS1MNqb6Za9zgHeWCiBqIC++Y+bkY= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
